name: test

on:
  push:
    branches:
      - main
  pull_request:
  schedule:  # Runs at 18:30 each day
    - cron: "30 18 * * *"
  workflow_dispatch:  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:  # Python > 3.11 blocked by grantjenks/py-tree-sitter-languages#85
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build
          pip install .[dev]

      - name: Run tests
        run: pytest
 
      - name: Build package
        run: python -m build
